# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build Project
        env:
          GITHUB_CONTEXT: ${{ toJson(github)}}
          GITHUB_ACTOR: ${{ github.actor}}
          GITHUB_EMAIL: ${{ github.event.commits[0].committer.email}} #FIXME
        run: |
          npm install
          npm run build

      - name: Deploy Project
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.BLOG  }}
          publish_dir: ./public
          publish_branch: master
